"""
planning/models.py - Core domain models for goal-oriented planning.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class GoalStatus(str, Enum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    WAITING = "WAITING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TaskStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


@dataclass
class Goal:
    """Represents a user objective."""
    description: str
    priority: str = "MEDIUM"  # e.g., LOW, MEDIUM, HIGH, CRITICAL
    deadline: datetime | None = None
    confidence: float = 1.0
    status: GoalStatus = GoalStatus.PENDING
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class Task:
    """Represents an atomic step to achieve a goal."""
    goal_id: str
    description: str
    tool: str
    parameters: dict[str, Any]
    dependencies: list[str] = field(default_factory=list)  # list of task IDs
    priority: str = "MEDIUM"
    status: TaskStatus = TaskStatus.PENDING
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    result: Any | None = None


@dataclass
class ExecutionStep:
    """An execution step to be run by the ExecutionEngine. Maps from a Task."""
    task_id: str
    tool: str
    parameters: dict[str, Any]
    description: str


@dataclass
class Plan:
    """A sequence of tasks generated by the planner to fulfill a goal."""
    tasks: list[Task] = field(default_factory=list)
    confidence: float = 1.0
    missing_information: list[str] = field(default_factory=list)
    is_multi_step: bool = False
